#!/usr/bin/env python3
"""
update_hot.py
=============
Regenerates wiki/hot.md — the auto-generated "current state" snapshot — from
wiki/log.md (and the experiment index, if present).

Design goals:
  - stdlib only, no external deps;
  - NEVER crash a session: every file read is best-effort, missing files fall back
    to sane defaults;
  - PRESERVE the hand-editable "Next Actions" block across regenerations (kept
    between the NEXT-ACTIONS:START / END markers).

Run manually:  python wiki/update_hot.py
It is also invoked automatically by the Stop hook in .claude/settings.json.
"""
from __future__ import annotations

import datetime as _dt
import re
from pathlib import Path

WIKI = Path(__file__).resolve().parent
LOG = WIKI / "log.md"
HOT = WIKI / "hot.md"
INDEX = WIKI / "index.md"
EXPERIMENTS = WIKI / "experiments"

N_RECENT = 8  # how many recent log lines to surface

NA_START = "<!-- NEXT-ACTIONS:START -->"
NA_END = "<!-- NEXT-ACTIONS:END -->"

DEFAULT_NEXT_ACTIONS = f"""{NA_START}
## Next Actions

_This block is hand-editable and preserved across regenerations._

- [ ] (add the current to-do list here)
{NA_END}"""

_LOG_LINE = re.compile(r"^## \[(\d{4}-\d{2}-\d{2})\]")


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except Exception:
        return ""


def recent_log_entries(text: str, n: int = N_RECENT) -> list[str]:
    """Return the last n lines that look like dated log entries."""
    entries = [ln.rstrip() for ln in text.splitlines() if _LOG_LINE.match(ln)]
    return entries[-n:]


def extract_next_actions(hot_text: str) -> str:
    """Pull the existing Next Actions block (inclusive of markers), or default."""
    if NA_START in hot_text and NA_END in hot_text:
        start = hot_text.index(NA_START)
        end = hot_text.index(NA_END) + len(NA_END)
        block = hot_text[start:end].strip()
        if block:
            return block
    return DEFAULT_NEXT_ACTIONS


def experiment_summary() -> str:
    """Best-effort count of experiment pages + their verdicts from frontmatter."""
    try:
        pages = sorted(EXPERIMENTS.glob("*.md"))
    except Exception:
        pages = []
    if not pages:
        return "- Experiments on record: see [index.md](index.md)."
    verdicts: dict[str, int] = {}
    for p in pages:
        txt = _read(p)
        m = re.search(r"^verdict:\s*(\S+)", txt, re.MULTILINE)
        v = m.group(1) if m else "unknown"
        verdicts[v] = verdicts.get(v, 0) + 1
    tally = ", ".join(f"{k}: {n}" for k, n in sorted(verdicts.items()))
    return f"- Experiments on record: **{len(pages)}** ({tally}). See [index.md](index.md)."


def build_hot() -> str:
    today = _dt.date.today().isoformat()
    log_text = _read(LOG)
    recent = recent_log_entries(log_text)
    next_actions = extract_next_actions(_read(HOT))
    exp_line = experiment_summary()

    recent_md = "\n".join(recent) if recent else "_(no log entries yet)_"

    return f"""<!-- ============================================================= -->
<!-- AUTO-GENERATED by wiki/update_hot.py - DO NOT HAND-EDIT.       -->
<!-- Your edits WILL be overwritten on the next run. The only       -->
<!-- editable region is the "Next Actions" block below, which the    -->
<!-- generator preserves across regenerations.                       -->
<!-- ============================================================= -->

# Hot - current state

_Last generated: {today} by update_hot.py._

## Current State

{exp_line}
- Project pivot in progress: from single-asset **direction** (no edge, AUC ~ 0.51-0.52)
  toward **cross-sectional / breadth** strategies (IR ~ IC*sqrt(N)). See [lessons.md](lessons.md).

## Recent Activity

{recent_md}

{next_actions}
"""


def main() -> int:
    try:
        HOT.write_text(build_hot(), encoding="utf-8")
        print(f"[update_hot] wrote {HOT}")
    except Exception as exc:  # never break a session
        print(f"[update_hot] skipped (non-fatal): {exc}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
